### ISSUE TITLE
Enable wrench debugging

### ISSUE THREAD

**Issue by zakorgy** [szeged/webrender#17] opened 2017-05-15 12:17 UTC
Running the reftests returns with the following errors:
```rust
error[E0432]: unresolved import `webrender::renderer::CpuProfile`
  --> src/wrench.rs:24:27
   |
24 | use webrender::renderer::{CpuProfile, GpuProfile};
   |                           ^^^^^^^^^^ no `CpuProfile` in `renderer`

error[E0432]: unresolved import `webrender::renderer::GpuProfile`
  --> src/wrench.rs:24:39
   |
24 | use webrender::renderer::{CpuProfile, GpuProfile};
   |                                       ^^^^^^^^^^ no `GpuProfile` in `renderer`

error: no method named `set_profiler_enabled` found for type `webrender::Renderer` in the current scope
   --> src/main.rs:515:41
    |
515 |                         wrench.renderer.set_profiler_enabled(profiler);
    |                                         ^^^^^^^^^^^^^^^^^^^^

error: no method named `gl` found for type `webrender::Renderer` in the current scope
  --> src/png.rs:58:32
   |
58 |     let data = wrench.renderer.gl().read_pixels(0,
   |                                ^^

error[E0277]: the trait bound `[u8]: std::marker::Sized` is not satisfied
  --> src/png.rs:58:9
   |
58 |     let data = wrench.renderer.gl().read_pixels(0,
   |         ^^^^ the trait `std::marker::Sized` is not implemented for `[u8]`
   |
   = note: `[u8]` does not have a constant size known at compile-time
   = note: all local variables must have a statically known size

error[E0308]: mismatched types
   --> src/wrench.rs:180:69
    |
180 |         let (renderer, sender) = webrender::renderer::Renderer::new(window.clone_gl(), opts, size).unwrap();
    |                                                                     ^^^^^^^^^^^^^^^^^ expected reference, found struct `std::rc::Rc`
    |
    = note: expected type `&glutin::Window`
               found type `std::rc::Rc<gleam::gl::Gl + 'static>`

error: no method named `gl` found for type `webrender::Renderer` in the current scope
   --> src/wrench.rs:194:35
    |
194 |         let gl_version = renderer.gl().get_string(gl::VERSION);
    |                                   ^^

error: no method named `gl` found for type `webrender::Renderer` in the current scope
   --> src/wrench.rs:195:36
    |
195 |         let gl_renderer = renderer.gl().get_string(gl::RENDERER);
    |                                    ^^

error: no method named `gl` found for type `webrender::Renderer` in the current scope
   --> src/wrench.rs:357:27
    |
357 |             self.renderer.gl().viewport(0, 0, dim.width as i32, dim.height as i32);
    |                           ^^

error: no method named `get_frame_profiles` found for type `webrender::Renderer` in the current scope
   --> src/wrench.rs:385:23
    |
385 |         self.renderer.get_frame_profiles()
    |                       ^^^^^^^^^^^^^^^^^^

error: no method named `debug_renderer` found for type `webrender::Renderer` in the current scope
   --> src/wrench.rs:407:32
    |
407 |         let dr = self.renderer.debug_renderer();
    |                                ^^^^^^^^^^^^^^
```
The following steps required:
- [ ] Reenable the CpuProfile and GpuProfile if necessary.
- [x] Replace `renderer.gl()` related calls

**Comment by kvark** [comment] 2017-05-18 21:45
Should be easier once https://github.com/servo/webrender/pull/1274 gets merged

**Comment by dati91** [comment] 2017-05-25 12:12
https://github.com/dati91/webrender/commit/681dffa282c3fec02758db61f1575f4eb1c3bef8
The `read_pixels` works.
We started to handle the Optional stride param with update texture, (servo didn't use it (at least we didn't find a use case yet)).
But the reftests use it, and something not quite right with our calculation. It seems like as if we draw the 3/4 correctly, and 1/4 wrong. I planning to revisit our mostly "hack-ish" solution for image update, we surely not prepared for this `row_length` properly.

The ref img
![tile-repeat-prim-or-decompose-ref yaml](https://cloud.githubusercontent.com/assets/2149430/26449615/78cd66c6-4153-11e7-88c3-3d2fbce782ed.png)
Our img 
![tile-repeat-prim-or-decompose yaml](https://cloud.githubusercontent.com/assets/2149430/26449617/7c91176c-4153-11e7-8987-3881cec9e955.png)

and with an other example
The ref img
![tile-size-ref yaml](https://cloud.githubusercontent.com/assets/2149430/26449660/c172635e-4153-11e7-9d90-d74053ec2709.png)
Our img
![tile-size yaml](https://cloud.githubusercontent.com/assets/2149430/26449666/c7e44d9c-4153-11e7-9313-ad2f0df4852f.png)

**Comment by kvark** [comment] 2017-05-25 13:26
Interesting! Could you provide `apitrace` captures for comparison?

**Comment by dati91** [comment] 2017-05-25 14:32
[wrench.zip](https://github.com/szeged/webrender/files/1029283/wrench.zip)

**Comment by kvark** [comment] 2017-05-25 18:17
I rewrote `update_texture` in https://github.com/kvark/webrender/commit/50b139aa1118a31cc60b3d7140a2461d2771d040
Fairly confident this part is functioning correctly now. There are problems elsewhere.
Please continue investigation and ping back if you are stuck.

**Comment by dati91** [comment] 2017-05-29 11:42
I can confirm that the `update_texture` works fine (with a [minor fix](https://github.com/dati91/webrender/commit/ea37a095f6c5ced905772e16bca41c5120f6d159#diff-d058594280164bb23d9b1ca25ba9fe79R742)).
It seems like the problem is related to [`tile_spacing`](https://github.com/dati91/webrender/blob/reftest/webrender_traits/src/display_list.rs#L520).
It can be reproduced easily, just change any of the blob example's tiling to any non-zero tiling.
If the first blob img tiling changed, it will remove the whole second img.
If the second blob img tiling changed, it will remove the first rect of the img.
![blob_tiling](https://cloud.githubusercontent.com/assets/2149430/26548414/5d224c1a-4474-11e7-9d8e-637296edb1f7.PNG)

**Comment by zakorgy** [comment] 2017-06-20 10:46
Calling flush after the draw call in submit_batch in renderer.rs solved the above issue.
![blob1](https://user-images.githubusercontent.com/11725775/27329608-7ea41258-55b6-11e7-971c-d7ef3a7a6c22.png)

**Comment by dati91** [comment] 2017-06-22 14:26
The `tiling` issue can be reproduced if you change the the [`tiling` value](https://github.com/servo/webrender/blob/master/webrender/examples/blob.rs#L251) in the blob example (e.g. (20.0, 20.0)). You can try it with one of our [older revision](https://github.com/szeged/webrender/tree/gfx-wr-c003d55-0525).

**Comment by kvark** [comment] 2017-06-22 20:22
@dati91 Thanks! I was able to repro.
The issue is related to synching the upload buffer, looking still...

**Comment by kvark** [comment] 2017-06-22 21:34
@dati91 I figured it out. It's not gfx-rs caching being broken, everything works as expected. It's how you do mapping:
```rust
    pub fn draw(...) {
            let mut writer = self.factory.write_mapping(&program.upload).unwrap();
            for (i, inst) in instances.iter().enumerate() {
                writer[i].update(inst);
            }

        self.encoder.copy_buffer(&program.upload, &program.data.ibuf, 0, 0, program.upload.len()).unwrap();
        self.encoder.draw(&program.slice, ...);
    }
```

Each draw writes the first N instances into the same upload buffer of the program. Then issues the `copy_buffer` command. The encoder just queues those copies, so the actual read of the data happens at `flush` later on. Thus, if you do another `draw()` call, it will overwrite some of the instances designated for the earlier made call. That's why flushing on each call worked around the issue for you - it ensures that the instance upload buffer actually gets read and written in sync.

I created https://github.com/gfx-rs/gfx/issues/1334 to detect the mis-use of upload buffers in the future.

What you want to do is - append to the upload buffer instead of overwriting it from the beginning on each draw call, and reset at the end/start of a frame. Of course, you'd need to pass the proper offset to data into `copy_buffer`, just don't overwrite anything until you flush.

**Comment by zakorgy** [comment] 2017-08-24 12:17
We wanted to connect our current dx11 code with wrench and run the reftests [here](https://github.com/zakorgy/webrender/commit/bf6bf00abeac8daf82692ba57f84706ee1fad793).
Unfortunately the [copy_texture_to_buffer_raw ](https://github.com/zakorgy/webrender/commit/bf6bf00abeac8daf82692ba57f84706ee1fad793#diff-d058594280164bb23d9b1ca25ba9fe79R389) has a missing implementation in gfx in the dx11 backend [here](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/src/command.rs#L348). 
cc @kvark

**Closed** 2017-10-20 10:18 UTC
